id = "apex"
name = "Apex"
version = "0.1.0"
authors = ["brianevanmiller"]
description = "Provides Salesforce Apex syntax highlighting for Zed"
repository = "https://github.com/brianevanmiller/zed-sfapex"
schema_version = 1

[grammars.apex]
repository = "https://github.com/aheber/tree-sitter-sfapex"
rev = "3597575a429766dd7ecce9f5bb97f6fec4419d5d"
path = "apex"
