id = "apex"
name = "Apex"
version = "0.0.1"
authors = ["brianevanmiller"]
description = "Provides Salesforce Apex syntax highlighting for Zed"
repository = "https://github.com/brianevanmiller/zed-sfapex"
schema_version = 1

[grammars.apex]
repository = "https://github.com/aheber/tree-sitter-sfapex"
commit = "c99ad4b16d112fea91745e3f1b769754239fdaba"
path = "apex"
